/** @format */

import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { google } from 'googleapis';
import React from 'react';

export default function Home({ res }) {
	React.useEffect(() => {
		console.log(res);
	}, []);

	return (
		<>
			<Head>
				<title>Izzul's Lab</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={styles.main}>
				<div>Welcome!</div>
			</main>
		</>
	);
}

export async function getServerSideProps() {
	const auth = await google.auth.getClient({
		scopes: ['https://www.googleapis.com/auth/spreadsheets.readonly'],
	});

	const sheets = google.sheets({ version: 'v4', auth });

	const range = `Sheet1!A1:B10`;

	const response = await sheets.spreadsheets.values.get({
		spreadsheetId: process.env.SHEET_ID,
		range,
	});

	console.log(response.data.values);

	const res = response.data.values;

	return {
		props: {
			res,
		},
	};
}
